### PR TITLE
Ensure that the code for api_module is loaded.

### LINKED ISSUE #35: UndefinedFunctionError during start-up of retriever
Environment: Elixir 1.5.2, OTP 20.1, ex_money 0.8.2

With the following config:
```
config :ex_money,
  exchange_rate_service: true,
  exchange_rates_retrieve_every: 3_600_000,
  open_exchange_rates_app_id: "APP_ID",
  log_success: :debug
```

this occurs during application startup
```
2017-11-09 15:09:38.304 [warn] Starting exchange rate retrieval service
2017-11-09 15:09:38.304 [warn] Initializing retrieval module Money.ExchangeRates.OpenExchangeRates
2017-11-09 15:09:38.305 [warn] Rates will be retrieved in 1 seconds and then every 3600 seconds.
2017-11-09 15:09:38.349 [error] GenServer Money.ExchangeRates.Retriever terminating
** (UndefinedFunctionError) function nil.url/0 is undefined (module nil is not available)
    nil.url()
    (ex_money) lib/money/exchange_rates/open_exchange_rates.ex:71: Money.ExchangeRates.OpenExchangeRates.get_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:56: Money.ExchangeRates.Retriever.retrieve_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:50: Money.ExchangeRates.Retriever.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :latest
State: %Money.ExchangeRates.Config{api_module: Money.ExchangeRates.OpenExchangeRates, callback_module: Money.ExchangeRates.Callback, delay_before_first_retrieval: 1000, log_levels: %{failure: :warn, info: :warn, success: :debug}, retrieve_every: 3600000, retriever_options: nil}
2017-11-09 15:09:39.728 [debug] Retrieved exchange rates successfully
```

I was able to get the call `Money.ExchangeRates.latest_rates` after the last log message.

### PR DESCRIPTION
**Pull request by blaketan**
# Summary
Fix #35 by ensuring that the code for retriever_api_module is loaded.

### CODE REVIEW

**Comment by kipcole9** [comment]
@blaketan thanks much.  Merged and pushed to hex as 0.8.5.

**Comment by blaketan** [comment]
Awesome!

**Comment by blaketan** [comment]
@kipcole9 Looks like the hex release has additional code in Money.Application that is causing compilation to fail:
```
==> ex_money
Compiling 13 files (.ex)

== Compilation error in file lib/money/application.ex ==
** (SyntaxError) lib/money/application.ex:21: "do" is missing terminator "end". unexpected token: ")" at line 23
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
could not compile dependency :ex_money, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_money", update it with "mix deps.update ex_money" or clean it with "mix deps.clean ex_money"
```

**Comment by kipcole9** [comment]
Apologies, i changed some stuff between starting the hex push and entering my passphrase.  Not enough coffee yet.

I made a small change - the code now checks that the module is available and can be loaded before starting the supervisor so that the exchange rates service won’t start up unless the api_module is valid and Code.ensure_loaded/1.  I think this is a little more robust.

I have re-pushed to hex with the same version number 0.8.5 so that there isn’t a version on hex that won’t compile.  Not my finest hour.

**Comment by blaketan** [comment]
@kipcole9 No problem! Thanks for all your hard work on this package. I've verified that the current 0.8.5 release on Hex works for retrieving exchange rate information.

**Comment by kipcole9** [comment]
Thanks for the feedback and your collaboration.  I would have spent more time tracking down an non-existent race condition so it was a big help (and a bit of a D’oh moment).  Perfect timing too - this weekend I’m adding historic rate retrieval and named exchange rates so getting the initialisation fixed first was important.

Thanks again.

**Pull request merged**
