### PR TITLE
Allow division by money

### PR DESCRIPTION
**Pull request by maennchen**
I'd like the possibility to divide money by money. This PR provides the option.

### CODE REVIEW

**Comment by kipcole9** [comment]
Thanks for the PR, its much appreciated.  Would you mind letting me know the use case for money divided by money?  As I'm sure you are well aware, division is a tricky thing since precision can (and is) often lost which is bad enough for floats but really an issue for money.  For example:
```elixir
iex> x = Decimal.div Decimal.new("10"), Decimal.new("3")
#Decimal<3.333333333333333333333333333>
iex> Decimal.mult x, Decimal.new(3)
#Decimal<9.999999999999999999999999999>
```
If the use case makes sense then I would prefer to have the API be more like `Money.split/2` which at lease returns the remainder as well.  Or perhaps the API could be:
```
@spec Money.div(Money.t, Money.t) :: {:ok, Money.t} | {:precision_error, Money.t, remainder :: Money.t}
```
ie. the return tagged tuple could indicate a precision error.

I'd appreciate your feedback and thoughts.

**Comment by maennchen** [comment]
@kipcole9 We are currently implementing an api endpoint that can upgrade user subscriptions. Since we can only bill recurring charges if they are exactly the same amount every time via our payment provider this is the solution we came up with (by example, let's assume every month has exactly 28 days to simplify the problem):

The user gets a subscription "medium" (1 month lifetime) for 50$ on Jan 1. It would theoretically go on until the 28. of Jan. If he decides to upgrade to "large" for 100$ on 14. of Jan, the result would be this:

Since he has used only 14 days of his subscription, 25$ are left. The subscription next period is  3.57$ per day. Therefore he gets another 7 days on top.

Our code looks like this:

```elixir
with %Date{} = new_end_date <-
       calculate_end_date_for_initial_period(service_date, new_subscription_lifetime),
     days_left when is_integer(days_left) <- Timex.diff(old_end_date, service_date, :days),
     {:ok, %Money{} = old_rate_per_day} <-
       rate_per_day(old_start_date, old_end_date, old_subscription_price),
     {:ok, %Money{} = total_amount_left} <- Money.mult(old_rate_per_day, days_left),
     {:ok, %Money{amount: new_rate_per_day}} <-
       rate_per_day(service_date, new_end_date, new_subscription_price),
     {:ok, %Money{amount: raw_days_to_add}} <- Money.div(total_amount_left, new_rate_per_day),
     days_to_add <-
       raw_days_to_add
       |> Decimal.to_float()
       |> Float.ceil()
       |> Kernel.trunc(),
     %Date{} = date <- Timex.shift(service_date, days: days_to_add) do
  {:ok, date}
else
  _ -> :error
end
```

I would like to write it like this:

```elixir
with %Date{} = new_end_date <-
       calculate_end_date_for_initial_period(service_date, new_subscription_lifetime),
     days_left when is_integer(days_left) <- Timex.diff(old_end_date, service_date, :days),
     {:ok, %Money{} = old_rate_per_day} <-
       rate_per_day(old_start_date, old_end_date, old_subscription_price),
     {:ok, %Money{} = total_amount_left} <- Money.mult(old_rate_per_day, days_left),
     {:ok, %Money{} = new_rate_per_day} <-
       rate_per_day(service_date, new_end_date, new_subscription_price),
     {:ok, %Decimal{} = raw_days_to_add} <- Money.div(total_amount_left, new_rate_per_day),
     days_to_add <-
       raw_days_to_add
       |> Decimal.to_float()
       |> Float.ceil()
       |> Kernel.trunc(),
     %Date{} = date <- Timex.shift(service_date, days: days_to_add) do
  {:ok, date}
else
  _ -> :error
end
```

This is not a very good example for precision since we always convert to float and `ceil` it to whole days.

I can add a `precision_error` or implement `split`, I would like both of the solutions. (maybe we should provide both?)

A little nitpick on the typespec you wrote:

The result of a division of two money amounts does not have a currency anymore. Therefore it should return a plain `Decimal`.

Example from Maths: `9.8m/s * 7s = 68.6m` (The `/s` is removed from the result)

```elixir
@spec Money.div(Money.t, Money.t) :: {:ok, Decimal.t} | {:precision_error, Decimal.t, remainder :: Decimal.t}
```

**Comment by Schultzer** [comment]
@maennchen I think you are misunderstanding the spec.

I would argue that `money` should always return a `Money.t` even for the remainder it should never ever return a `Decimal.t` other then if it it explicit called, and even there we should properly return a `tuple` with the information.

the reason behind this is that we don't want to lose data structure if a developer only want the integer, float, decimal they should handle that in there own code base

I know that `Money.to_decimal/1` returns a `Decimal.t` but it should properly return a `tuple` with `{currency, decimal.t}`

**Comment by maennchen** [comment]
@Schultzer I don‘t really understand this reasoning. If I need the currency, can‘t I read it from the inputs I gave to the function?

I don‘t think that this makes sense (at least not mathematically).

Could you elaborate further?

**Comment by Schultzer** [comment]
I'm sorry for being clear enough.

Integer value of $100 USD is `10000` because you have an exponent of 2 witch are the cent
but some currency does not have and exponent and others has an exponent there is greater then 2
JPY exponent is 0.

We should never ever convert a `Money.t` to `Float.t` we will lose precision.

So there are only three ways we should convert `Money.t` to, that be `Integer.t`, `String.t` or `Decimal.t` and in those cases we will still want as much information as possible.

here is an example where we keep the structure in the `Decimal.t`
```elixir
{:USD, %Decimal{sign: 1, coef: 10000,  exp: -2}}
{:JPY, %Decimal{sign: 1, coef: 100,  exp: 0}}
```

I hope this answer your questions.

**Comment by Schultzer** [comment]
The reason why we loose precision with floats is that a `float` of say `10.00` is not represent as `10.00` internally it might be that it's is `9.999999999999999999999999999999999`
and that is basically why you don't want to use floats with anything that has to do with money.

**Comment by kipcole9** [comment]
Thanks for the explanation and I can understand how pro-rating subscription (up or down) would require this kind of computation.

There is a `Money.split/2` function which is intended to support this kind of calculation while also ensuring the right rounding for a currency is applied and any remainder correctly tagged.  It is documented below and I think expresses the intent better than `Money.div` would do (in my opinion).

I'd like to think on this a little more and would appreciate your thoughts on the below being applicable as well.

```
  Split a `Money` value into a number of parts maintaining the currency's
  precision and rounding and ensuring that the parts sum to the original
  amount.

  ## Options

  * `money` is a `%Money{}` struct

  * `parts` is an integer number of parts into which the `money` is split

  Returns a tuple `{dividend, remainder}` as the function result
  derived as follows:

  1. Round the money amount to the required currency precision using
  `Money.round/1`

  2. Divide the result of step 1 by the integer divisor

  3. Round the result of the division to the precision of the currency
  using `Money.round/1`

  4. Return two numbers: the result of the division and any remainder
  that could not be applied given the precision of the currency.

  ## Examples

      Money.split Money.new(123.5, :JPY), 3
      {¥41, ¥1}

      Money.split Money.new(123.4, :JPY), 3
      {¥41, ¥0}

      Money.split Money.new(123.7, :USD), 9
      {$13.74, $0.04}
```

**Comment by aphillipo** [comment]
Money.split would have to support a fraction as the second parameter to be really good here, i.e. ‘’’Money.split Money.new(100, :USD), 23/31’’’

**Comment by kipcole9** [comment]
I things your use case is worthy of being better encapsulated in `ex_money` than providing `Money.div/2` with which I am really uncomfortable.  Even your example of that day rate of the `medium` package being $3.57 introduces errors because `$3.57 * 14 = $49.98` not `$50`.  The accounting ends up in error unless you account for the `$0.02.

I'd prefer to build a `Money.Subscriptions` module that supports:
* Adding a subscription
* Upgrading a subscription
* Downgrading a subscription

### Upgrading or downgrading a subscription
When upgrading or downgrading a subscription there are considerations of how to account for the credit/debit left over; the period of the new subscription (co-terminates with a short first period or creates a new subscription from the current date) and what happens at the end of the new upgraded subscription,

1. A new subscription is created with either:

    * the first period payment being reduced/increased by the amount of the credit from the first subscription or
    * the credit period is held such that it is available if/when the new upgraded subscription is closed.  ie. when the upgraded subscription is close, the previous (medium in your example) subscription is reactivated for the period of time that can be supported by the outstanding credit.

2. The new subscription period is either
    * the date on which the upgrade occurred or
    * aligned to the date of the original subscription and hence the first period of the new subscription is shorter than the the others

3.  A subscription period is either
    * a fixed number of days
    * aligned to a calendar event (daily, weekly, monthly, quarter or yearly) or a multiple of the same

**Sorry for losing a few days on the conversation - but i'd appreciate your feedback on this.**  I believe implementing subscriptions this way I can maximise the retention of precision and better express the intent of subscription accounting. I can also make sure it works with multiple currencies and locales and potentially let you price in one currency and bill in another.

**Comment by maennchen** [comment]
> Even your example of that day rate of the medium package being $3.57 introduces errors because $3.57 * 14 = $49.98 not $50. The accounting ends up in error unless you account for the `$0.02.

My example is not very good because i just round everything up in favor of the customer. In our case that doesn't really matter.

If we would return the result and a remainder, that would fix the precision problem.

> I'd prefer to build a Money.Subscriptions module that supports:

I love the idea :)

Could we come up with a few test cases on paper before I actually implement any of this? It would help me because I'm sure that we mean the same thing in detail.

**Comment by kipcole9** [comment]
Very happy to collaborate.  I've been reading the [strip api documentation](https://stripe.com/docs/subscriptions/quickstart) as a starting point.  I would welcome your ideas and proposals.  I've started fleshing out the `Money.Subscriptions` module but it has a way to go so your feedback and use case can guide what I do next.

**Comment by maennchen** [comment]
@kipcole9 We should move to a dedicated issue for that. The PR seems to be the wrong place. I'm going to close for now.

**Pull request closed without merging**
